name: BattleKits
main: battlekits\BattleKits
version: 1.0.4
author: Falkirks
api: [2.0.0]
load: POSTWORLD
softdepend: ["EconomyAPI", "PocketMoney"]
permissions:
 battlekits:
  default: op
  children:
   battlekits.use:
    default: op
   battlekits.listkits:
    default: true
   battlekits.sign:
    default: op
    children:
     battlekits.sign.use:
      default: true
     battlekits.sign.create:
      default: op
